spring:
  datasource:
    url: jdbc:mysql://sql.freedb.tech/freedb_candy_store
    username: freedb_candy_store_user
    password: j*qy3av8KJ8v2Ug
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: freedb_candy_store
app:
  security:
    jwt:
      secret: c1pyNHU3eCFBJUQqRy1LYVBkU2dWa1lwM3M2djl5JGYpSkBOY1JmVWpYbjJyNXU4eC9BP0QoRytLYlBlU2hWbQ==
      expiration: 2_678_400_000
      refresh-expiration: 5_443_200_000