spring:
  datasource:
    url: jdbc:mysql://localhost:3306/candy_store
    username: root
    password: qwerty
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: candy_store
app:
  security:
    jwt:
      secret: c1pyNHU3eCFBJUQqRy1LYVBkU2dWa1lwM3M2djl5JGYpSkBOY1JmVWpYbjJyNXU4eC9BP0QoRytLYlBlU2hWbQ==
      expiration: 2_678_400_000
      refresh-expiration: 5_443_200_000
server:
  port: 8080

