spring:
  datasource:
    url: jdbc:mysql://localhost:3306/candy_store
    username: root
    password: qwerty
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    schemas: candy_store
  servlet:
    multipart:
      max-file-size: 5MB
logging:
  level:
    org.springframework.web: ERROR
  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: candy-store.log
app:
  security:
    jwt:
      secret: c1pyNHU3eCFBJUQqRy1LYVBkU2dWa1lwM3M2djl5JGYpSkBOY1JmVWpYbjJyNXU4eC9BP0QoRytLYlBlU2hWbQ==
      expiration: 2_678_400_000
      refresh-expiration: 5_443_200_000
  image:
    location: D:\Candy store\Images
    path: /api/v1/image?id=
  server-url: http://localhost:${server.port}
server:
  port: 8080